### ISSUE TITLE
V1.0.0 Overview

### ISSUE THREAD

**Issue by catfishlty** [catfishlty/mongodb-local-backup#1]
Aim to:
- [x] 1. using `mongoexport` tool to make backup data in local in *JSON* *CSV* format.
- [ ] 2. Support Linux, MacOS, Windows.
    - [x] Windows
    - [ ] Linux
    - [ ] MacOS
- [x] 3. Support *CronJob* to do the backup task.
- [x] 4. Document
    - [x] Chinese
    - [x] English
- [ ] 5. Build & CI & Cov & FOSSA
    - [x] godoc
    - [x] Github Actions
    - [ ] Travis CI
    - [x] CircleCI
    - [x] codecov
    - [x] goreport
- [x] 6. Automatic release
- [ ] 7. Support Docker
